### ISSUE TITLE
Dark Power box rev.2 design

### ISSUE THREAD

**Issue by kvijay1995** [IEEERobotics/bot2014#222]
needs a second revision for tolerances of holes using the laser cutter and with a friction fit of pieces

**Comment by amarron314** [comment]
Dark power case v2 is ready to be cut.
All the STEP files in the folder:
https://drive.google.com/drive/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA/0B93g4TjHMS2pRHNoWXRqdmhjaVk/0B17os4ifuU2VcVlyWFhYZVN3YjA/0B17os4ifuU2VWGp5WDVRejBOd1E/0B17os4ifuU2VbERLV3EtQVVUS2M

**Comment by whiteskulleton** [comment]
Finished cutting it. Putting it in the locker under important stuff.

**Comment by amarron314** [comment]
The left and right sides needed to be de-done because the resistor knobs were larger than anticipated. 
The updated  STEP files are in the folder:
https://drive.google.com/drive/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA/0B93g4TjHMS2pRHNoWXRqdmhjaVk/0B17os4ifuU2VcVlyWFhYZVN3YjA/0B17os4ifuU2VWGp5WDVRejBOd1E/0B17os4ifuU2VQjZQeFlfQ3ZVYmM

**Comment by whiteskulleton** [comment]
Cut it and put it in the cabinet
