### ISSUE TITLE
Senior Design proposal 

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#244]
Can everyone take a look at the senior design proposal.

Any feedback wold be a lot of help.
It will need to be turned in late tomorrow for this semester senior design.

This can be a big win for us.

Thanks.

**Comment by jasteve4** [comment]
Here is the link to the google drive:
https://drive.google.com/a/ncsu.edu/#folders/0B_fnIkF7_1pgSkNWTUlEOXg3M28

**Comment by dfarrell07** [comment]
I'd add a requirement that it's an Open Hardware and Open Source Software project with solid docs that should allow the community to replicate the board.

**Comment by jakunesh** [comment]
I agree with Daniel. Otherwise I fixed a few typos and I think it looks great!

**Comment by dfarrell07** [comment]
Maybe some protection-related stuff (/me defers details to ECE folks). For example, it should resist catching on fire if we drop a nut on it.

**Comment by dfarrell07** [comment]
PS - I love the idea of proposing this as a Senior Design project. Huge props to whoever came up with that.

**Comment by PaladinEng** [comment]
I accept beer in lieu of huge props.

**Comment by PaladinEng** [comment]
Do you all think it is feasible/worthwhile to include short/surge
protection so that the BBB is protected?

**Comment by R00ney** [comment]
Cool Idea.
Neal

**Comment by AhmedSamara** [comment]
Minor terminology dispute, but most of it keeps referring to the connectors (usb, ethernet, hdmi, etc) ports as "peripherals", which I've mostly seen used in the context of add-on devices (ie: the motor cape is a peripheral), so I think that might get confusing, so I'm slightly rephrasing a lot of it to use that.

Also, Spec#7 

> The peripherals shall be on top of the board (ie connectors, buttons, and any interfaces)

Doesn't make sense given spec5

>The cape shall be stackable (i.e. plug in multiple capes into the same beaglebone without issue)   

Since if they're on top of the word, so I think we should remove that one entirely. The only important thing is that connectors and accesses are accessible from the bone, which I think is a given if it's stackable.

**Comment by jasteve4** [comment]
Does any know were the flyer image is.

**Comment by SeanKetring** [comment]
If you mean the image that I made for the crankarm flyers here is a copy of
that file

On Mon, Jan 19, 2015 at 2:30 PM, jasteve4 <notifications@github.com> wrote:

> Does any know were the flyer image is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot2014/issues/244#issuecomment-70547456>
> .
>



-- 
Thank you, and have a good day!
Sean Ketring

Electrical Engineering Undergraduate

**Comment by AhmedSamara** [comment]
Nobody wanted us.
