### ISSUE TITLE
Arduino Needs to be set up so the IEEE Etch-a-Sketch can be tested for both motors

### ISSUE THREAD

**Issue by Sidd-GrizzAp3** [IEEERobotics/bot2014#286]
Mark fixed the rig so it can run both motors to the etch-a-sketch set up; however, he can't validate both motors at the same time for testing purposes, so if anyone can rig the arduino to run both motors at the same time, we can get to testing / start the software coding for this component of the competition! 

@psychomugs @whiteskulleton

**Comment by psychomugs** [comment]
This sketch draws IEEE as a diagonal:
https://gist.github.com/psychomugs/4b448301c15ab0e39627

This sketch draws IEEE inline. I personally do not prefer this method because the letters have a greater likelihood of interfering with each other, whereas that is almost impossible when drawing diagonally:
https://gist.github.com/psychomugs/9c41163290fde3af6b0c
