### ISSUE TITLE
H-bridge boards for Simon Says player   

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#311]
To support the five motors that are need for the Simon Says player, we need to create a motor controller board. I have two types of H-bridge ics. 

DRV8833
http://www.ti.com/lit/gpn/drv8833 

DRV8848
http://www.ti.com/lit/gpn/drv8848

It doesn't matter which ic we use. Each motor will need 2 GPIOs. This can be simulated by tying a pin to power or ground.

**Comment by jakunesh** [comment]
The motors have arrived

**Comment by AhmedSamara** [comment]
The basic circuit worked on a breadboard, but not when moved to a proto-board. We're pretty sure the issue is that nsleep was left floating, which is required to enable the H-bridge. 

@jasteve4 wired it correctly.

Here is what we believe is the current (and correct) configuration:

![image](https://cloud.githubusercontent.com/assets/2405319/6958710/a52412b4-d8dd-11e4-9fc6-7c0ed1abb5bc.png)

**Comment by AhmedSamara** [comment]
Also, another note: When we were debugging we continuously find a short between Vm and Vref.  
After a few hours of trying to find the issue on the board, we fixed the problem mentioned above and it started working again.  
The short is apparently internal and perfectly normal.  
The only thing that should be needed to correct the rest of them is tying nsleep to 3.3v

**Comment by jakunesh** [comment]
note: that diagram is incorrect. nFault is an output and should not be tied to anything except a GPIO if it's being used.
