### ISSUE TITLE
MAC address register with ncsu

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#316]
We need to register the mac address of the nics with the club. I need to make room for some of my devices.

**Comment by AhmedSamara** [comment]
I thought the MAC address was specific to the individual Beaglebone?

Regardless, The website for manually registering them is [here](http://webapps.ncsu.edu/cyclone/campus/registration/device/).

And you can find your MAC address manually via `ifconfig`, but since you already have them registered, just go into your [nomad registration](https://nomad.ncsu.edu/) and copy the MAC addresses and I'll register them for you.

**Comment by dfarrell07** [comment]
> I thought the MAC address was specific to the individual Beaglebone?

MAC addresses are always specific to L2 NICs.

**Comment by jasteve4** [comment]
Thanks Ahmed and Danial, we should move this to a wiki so it will be easy to find when we are setting up the nics on any new bots.
