### ISSUE TITLE
Rubiks cube getting caught after exit.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#344]
![image](https://cloud.githubusercontent.com/assets/2405319/7060360/946af42c-de4d-11e4-9f22-a9a99f9589c6.png)

The power screw can grab and turn it just fine, but after it returns the grip on the mold is so tight that it gets caught in the gripper.

**Comment by AhmedSamara** [comment]
Actually, it doesn't always go in.

I think this can be solved by sanding/oiling the gripper, but I wanted to check with anyone else before I started tampering with hardware that didn't have backups.

**Comment by jdekler** [comment]
I believe the best way to deal with these problems is
1. Sand or file the receiving edges of the turning mechanism into a chamfer
or radiused edge so that the Rubik's doesn't catch but instead will slide
in.
2. I believe the reason it isn't working on turning is because last night I
moved the gripper assembly over to the left (facing the bot) in order to
avoid hitting the gripper stepper motor. I moved it over too far, so the
cube isn't fully seated in the corner when it is squeezed by the grippers.
To correct this just loosen the screws holding the white arms to the frame
and move to the left far enough that the cube is secure but the mechanism
doesn't contact the left gripper motor.

**Comment by AhmedSamara** [comment]
(This worked not that it ended up mattering).
